### ISSUE TITLE
起動時の環境変数

### ISSUE THREAD

**Issue by petitroto** [tktkbohshi/fairseq-jp-dialog-api#1]
質問させてください。
先にインストールしたjapanese-dialog-transformersディレクトリが
fairseq-jp-dialog-apiディレクトリと並列に存在する場合、起動の仕方は以下であっていますか？

```
DATA_PATH=../japanese-dialog-transformers/data/sample/bin \
MODEL_PATH=../japanese-dialog-transformers/checkpoints/japanese-dialog-transformer-1.6B-persona50k.pt \
bash flask-fairseq.sh
```

こちらでは、起動はするのですが、GETリクエストを投げるとエラーになって困っています。
何かお気付きのことがあればご指摘いただけますと助かります。

```
(base) fairseq-jp-dialog-api $ DATA_PATH=../japanese-dialog-transformers/data/sample/bin MODEL_PATH=../japanese-dialog-transformers/checkpoints/japanese-dialog-transformer-1.6B-persona50k.pt bash flask-fairseq.sh 
2021-12-20 19:22:47 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
# Load fairseq configurations and a model
2021-12-20 19:22:49 | INFO | fairseq.tasks.translation | [src] dictionary: 32002 types
2021-12-20 19:22:49 | INFO | fairseq.tasks.translation | [dst] dictionary: 32002 types
# Load flask configuration
 * Serving Flask app 'flask_main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2021-12-20 19:23:24 | INFO | werkzeug |  * Running on http://localhost:5000/ (Press CTRL+C to quit)
2021-12-20 19:23:24 | INFO | werkzeug |  * Restarting with stat
2021-12-20 19:23:25 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
# Load fairseq configurations and a model
2021-12-20 19:23:27 | INFO | fairseq.tasks.translation | [src] dictionary: 32002 types
2021-12-20 19:23:27 | INFO | fairseq.tasks.translation | [dst] dictionary: 32002 types
# Load flask configuration
2021-12-20 19:24:03 | WARNING | werkzeug |  * Debugger is active!
2021-12-20 19:24:03 | INFO | werkzeug |  * Debugger PIN: 595-712-541
None
2021-12-20 19:30:35 | INFO | werkzeug | 127.0.0.1 - - [20/Dec/2021 19:30:35] "GET /get_response HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/nakamura/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/nakamura/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/nakamura/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nakamura/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nakamura/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nakamura/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/nakamura/tmp/fairseq-jp-dialog-api/scripts/flask_main.py", line 29, in return_message
    received_message = arg["message"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by tktkbohshi** [comment]
通信は問題なくこなせていて，送信したデータが正しく受け渡せていないようなので，これはリクエスト側の問題かと思います（今日pythonのrequestsモジュールからリクエストを送ろうとしていた時に同じエラーに遭遇しました）．
できればGETリクエストをどう送ったか教えていただけるとこちらでも対処できると思います．

参考までにrequestsモジュールからgetリクエストを送る場合は，
```
sendingData = {"message": utterance}
# send request
res = requests.get("http://localhost:5000/get_response", json=sendingData)
```
のように，引数にjsonを指定してdictを渡せばエラー回避できました．

ひとまずご参考になれば幸いです

**Comment by tktkbohshi** [comment]
ターミナル上で`curl -XGET -d '{"message":"Hello!"}' -H "Content-Type: application/json" http://localhost:5000/get_response`が通れば，ローカルサーバーは問題なく立ち上がっているはずです．

**Comment by petitroto** [comment]
@tktkbohshi 早速のお返事ありがとうございます！解決しました。

原因は、HTTPリクエストボディ内のUnicode文字列がエスケープされているかどうかの違いでした。

エスケープされてないとダメで

```
{ message: '今日は寒いですね。' }
```

エスケープされていれば通りました。

```
{"message": "\u4ECA\u65E5\u306F\u5BD2\u3044\u3067\u3059\u306D\u3002"}
```

教えていただいたPythonのrequestsモジュールだと、勝手にエスケープしてくれるようです。
Node.jsのaxiosで送ると、勝手にはエスケープしないので、自分でエスケープして送ると通りました。
ありがとうございました！
